# Generated by Django 5.2.1 on 2025-05-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FruitVeggie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='蔬果名称（中文）')),
                ('name_en', models.CharField(max_length=100, verbose_name='蔬果名称（英文）')),
                ('sugar_content', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='含糖量 (每100克)')),
                ('gi_index', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='升糖指数 (GI)')),
            ],
            options={
                'verbose_name': '蔬果数据',
                'verbose_name_plural': '蔬果数据',
            },
        ),
    ]
