# Generated by Django 5.2.1 on 2025-05-17 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jtapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruitveggie',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='蔬果英文名'),
        ),
    ]
