# Generated by Django 5.2.1 on 2025-05-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jtapp', '0002_alter_fruitveggie_name_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruitveggie',
            name='category',
            field=models.CharField(choices=[('vegetable', '蔬菜'), ('fruit', '水果')], default='fruit', max_length=10, verbose_name='类别'),
            preserve_default=False,
        ),
    ]
