# Generated by Django 5.2.1 on 2025-05-17 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jtapp', '0003_fruitveggie_category'),
    ]

    operations = [
    ]
